package com.checkdesk.model.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Answers generated by hbm2java
 */
public class Answer
        implements java.io.Serializable
{
    private int id;
    private Survey survey;
    private User owner;
    private String feedback;
    private Date occurredDate;
    private Set questionAnswers = new HashSet(0);
    private Set rankStatements = new HashSet(0);

    public Answer()
    {
    }

    public Answer(int id, Survey survey, User owner, String feedback, Date occurredDate)
    {
        this.id = id;
        this.survey = survey;
        this.owner = owner;
        this.feedback = feedback;
        this.occurredDate = occurredDate;
    }

    public Answer(int id, Survey survey, User owner, String feedback, Date occurredDate, Set questionAnswers, Set rankStatements)
    {
        this.id = id;
        this.survey = survey;
        this.owner = owner;
        this.feedback = feedback;
        this.occurredDate = occurredDate;
        this.questionAnswers = questionAnswers;
        this.rankStatements = rankStatements;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Survey getSurvey()
    {
        return this.survey;
    }

    public void setSurvey(Survey survey)
    {
        this.survey = survey;
    }

    public User getOwner()
    {
        return this.owner;
    }

    public void setOwner(User owner)
    {
        this.owner = owner;
    }

    public String getFeedback()
    {
        return this.feedback;
    }

    public void setFeedback(String feedback)
    {
        this.feedback = feedback;
    }

    public Date getOccurredDate()
    {
        return this.occurredDate;
    }

    public void setOccurredDate(Date occurredDate)
    {
        this.occurredDate = occurredDate;
    }

    public Set getQuestionAnswers()
    {
        return this.questionAnswers;
    }

    public void setQuestionAnswers(Set questionAnswers)
    {
        this.questionAnswers = questionAnswers;
    }

    public Set getRankStatements()
    {
        return this.rankStatements;
    }

    public void setRankStatements(Set rankStatements)
    {
        this.rankStatements = rankStatements;
    }
}
