package com.checkdesk.model.data;
// Generated Oct 21, 2018 7:39:33 PM by Hibernate Tools 4.3.1



/**
 * OptionItem generated by hbm2java
 */
public class OptionItem  implements java.io.Serializable {


     private int id;
     private Option option;
     private String name;
     private String value;

    public OptionItem() {
    }

    public OptionItem(Option option, String name, String value) {
       this.option = option;
       this.name = name;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Option getOption() {
        return this.option;
    }
    
    public void setOption(Option option) {
        this.option = option;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


