package com.checkdesk.model.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

/**
 * OptionItens generated by hbm2java
 */
public class OptionItem
        implements java.io.Serializable
{
    private int id;
    private Option option;
    private String name;
    private String value;

    public OptionItem()
    {
    }

    public OptionItem(int id, Option option, String name, String value)
    {
        this.id = id;
        this.option = option;
        this.name = name;
        this.value = value;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Option getOption()
    {
        return this.option;
    }

    public void setOption(Option option)
    {
        this.option = option;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }
}
