package com.checkdesk.model.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Surveys generated by hbm2java
 */
public class Survey
        implements java.io.Serializable
{
    public static final int TYPE_PUBLIC    = 0;
    public static final int TYPE_PRIVATE   = 1;
    public static final int TYPE_ANONYMOUS = 2;
    public static final int TYPE_TOTEM     = 3;
    
    private int id;
    private Category category;
    private Form form;
    private Group viewers;
    private Group participants;
    private User owner;
    private String title;
    private String info;
    private Date createdDate;
    private int type;
    private Set answers = new HashSet(0);

    public Survey()
    {
    }

    public Survey(int id, Category category, Form form, User owner, String title, String info, Date createdDate, int type)
    {
        this.id = id;
        this.category = category;
        this.form = form;
        this.owner = owner;
        this.title = title;
        this.info = info;
        this.createdDate = createdDate;
        this.type = type;
    }

    public Survey(int id, Category category, Form form, Group viewers, Group participants, User owner, String title, String info, Date createdDate, int type, Set answers)
    {
        this.id = id;
        this.category = category;
        this.form = form;
        this.viewers = viewers;
        this.participants = participants;
        this.owner = owner;
        this.title = title;
        this.info = info;
        this.createdDate = createdDate;
        this.type = type;
        this.answers = answers;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Category getCategory()
    {
        return this.category;
    }

    public void setCategory(Category category)
    {
        this.category = category;
    }

    public Form getForm()
    {
        return this.form;
    }

    public void setForm(Form form)
    {
        this.form = form;
    }

    public Group getViewers()
    {
        return this.viewers;
    }

    public void setViewers(Group viewers)
    {
        this.viewers = viewers;
    }

    public Group getParticipants()
    {
        return this.participants;
    }

    public void setParticipants(Group participants)
    {
        this.participants = participants;
    }

    public User getOwner()
    {
        return this.owner;
    }

    public void setOwner(User owner)
    {
        this.owner = owner;
    }

    public String getTitle()
    {
        return this.title;
    }

    public void setTitle(String title)
    {
        this.title = title;
    }

    public String getInfo()
    {
        return this.info;
    }

    public void setInfo(String info)
    {
        this.info = info;
    }

    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate)
    {
        this.createdDate = createdDate;
    }

    public int getType()
    {
        return this.type;
    }

    public void setType(int type)
    {
        this.type = type;
    }

    public Set getAnswers()
    {
        return this.answers;
    }

    public void setAnswers(Set answers)
    {
        this.answers = answers;
    }
}
