package com.checkdesk.model.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class User
        implements java.io.Serializable
{
    private int id;
    private String name;
    private String login;
    private String email;
    private String password;
    private String phone;
    private int type;
    private Set logs = new HashSet(0);
    private Set answers = new HashSet(0);
    private Set surveys = new HashSet(0);
    private Set categories = new HashSet(0);
    private Set rankStatements = new HashSet(0);
    private Set groups = new HashSet(0);

    public User()
    {
    }

    public User(int id, String name, String login, String email, String password, String phone, int type)
    {
        this.id = id;
        this.name = name;
        this.login = login;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.type = type;
    }

    public User(int id, String name, String login, String email, String password, String phone, int type, Set logs, Set answers, Set surveys, Set categories, Set rankStatements, Set groups)
    {
        this.id = id;
        this.name = name;
        this.login = login;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.type = type;
        this.logs = logs;
        this.answers = answers;
        this.surveys = surveys;
        this.categories = categories;
        this.rankStatements = rankStatements;
        this.groups = groups;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getLogin()
    {
        return this.login;
    }

    public void setLogin(String login)
    {
        this.login = login;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getPhone()
    {
        return this.phone;
    }

    public void setPhone(String phone)
    {
        this.phone = phone;
    }

    public int getType()
    {
        return this.type;
    }

    public void setType(int type)
    {
        this.type = type;
    }

    public Set getLogs()
    {
        return this.logs;
    }

    public void setLogs(Set logs)
    {
        this.logs = logs;
    }

    public Set getAnswers()
    {
        return this.answers;
    }

    public void setAnswers(Set answers)
    {
        this.answers = answers;
    }

    public Set getSurveys()
    {
        return this.surveys;
    }

    public void setSurveys(Set surveys)
    {
        this.surveys = surveys;
    }

    public Set getCategories()
    {
        return this.categories;
    }

    public void setCategories(Set categories)
    {
        this.categories = categories;
    }

    public Set getRankStatements()
    {
        return this.rankStatements;
    }

    public void setRankStatements(Set rankStatements)
    {
        this.rankStatements = rankStatements;
    }

    public Set getGroups()
    {
        return this.groups;
    }

    public void setGroups(Set groups)
    {
        this.groups = groups;
    }
}
