package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private int id;
     private Surveys surveys;
     private Users users;
     private String feedback;
     private Date dtOccurred;
     private Set rankStatementses = new HashSet(0);
     private Set questionAnswerses = new HashSet(0);

    public Answers() {
    }

	
    public Answers(int id, Surveys surveys, Users users, String feedback, Date dtOccurred) {
        this.id = id;
        this.surveys = surveys;
        this.users = users;
        this.feedback = feedback;
        this.dtOccurred = dtOccurred;
    }
    public Answers(int id, Surveys surveys, Users users, String feedback, Date dtOccurred, Set rankStatementses, Set questionAnswerses) {
       this.id = id;
       this.surveys = surveys;
       this.users = users;
       this.feedback = feedback;
       this.dtOccurred = dtOccurred;
       this.rankStatementses = rankStatementses;
       this.questionAnswerses = questionAnswerses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Surveys getSurveys() {
        return this.surveys;
    }
    
    public void setSurveys(Surveys surveys) {
        this.surveys = surveys;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public Date getDtOccurred() {
        return this.dtOccurred;
    }
    
    public void setDtOccurred(Date dtOccurred) {
        this.dtOccurred = dtOccurred;
    }
    public Set getRankStatementses() {
        return this.rankStatementses;
    }
    
    public void setRankStatementses(Set rankStatementses) {
        this.rankStatementses = rankStatementses;
    }
    public Set getQuestionAnswerses() {
        return this.questionAnswerses;
    }
    
    public void setQuestionAnswerses(Set questionAnswerses) {
        this.questionAnswerses = questionAnswerses;
    }




}


