package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private UserGroups userGroups;
     private Users users;
     private String name;
     private String info;
     private Set categorieses = new HashSet(0);
     private Set surveyses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int id, Users users, String name, String info) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.info = info;
    }
    public Categories(int id, Categories categories, UserGroups userGroups, Users users, String name, String info, Set categorieses, Set surveyses) {
       this.id = id;
       this.categories = categories;
       this.userGroups = userGroups;
       this.users = users;
       this.name = name;
       this.info = info;
       this.categorieses = categorieses;
       this.surveyses = surveyses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public UserGroups getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(UserGroups userGroups) {
        this.userGroups = userGroups;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }
    public Set getSurveyses() {
        return this.surveyses;
    }
    
    public void setSurveyses(Set surveyses) {
        this.surveyses = surveyses;
    }




}


