package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Forms generated by hbm2java
 */
public class Forms  implements java.io.Serializable {


     private int id;
     private UserGroups userGroups;
     private String name;
     private String info;
     private Set surveyses = new HashSet(0);
     private Set questionses = new HashSet(0);

    public Forms() {
    }

	
    public Forms(int id, String name, String info) {
        this.id = id;
        this.name = name;
        this.info = info;
    }
    public Forms(int id, UserGroups userGroups, String name, String info, Set surveyses, Set questionses) {
       this.id = id;
       this.userGroups = userGroups;
       this.name = name;
       this.info = info;
       this.surveyses = surveyses;
       this.questionses = questionses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public UserGroups getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(UserGroups userGroups) {
        this.userGroups = userGroups;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set getSurveyses() {
        return this.surveyses;
    }
    
    public void setSurveyses(Set surveyses) {
        this.surveyses = surveyses;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }




}


