package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs  implements java.io.Serializable {


     private int id;
     private Users users;
     private int event;
     private String objectName;
     private String objectClass;
     private String command;
     private Date date;

    public Logs() {
    }

    public Logs(int id, Users users, int event, String objectName, String objectClass, String command, Date date) {
       this.id = id;
       this.users = users;
       this.event = event;
       this.objectName = objectName;
       this.objectClass = objectClass;
       this.command = command;
       this.date = date;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getEvent() {
        return this.event;
    }
    
    public void setEvent(int event) {
        this.event = event;
    }
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }
    public String getObjectClass() {
        return this.objectClass;
    }
    
    public void setObjectClass(String objectClass) {
        this.objectClass = objectClass;
    }
    public String getCommand() {
        return this.command;
    }
    
    public void setCommand(String command) {
        this.command = command;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


