package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1



/**
 * OptionItens generated by hbm2java
 */
public class OptionItens  implements java.io.Serializable {


     private int id;
     private Options options;
     private String name;
     private String value;

    public OptionItens() {
    }

    public OptionItens(int id, Options options, String name, String value) {
       this.id = id;
       this.options = options;
       this.name = name;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Options getOptions() {
        return this.options;
    }
    
    public void setOptions(Options options) {
        this.options = options;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


