package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Options generated by hbm2java
 */
public class Options  implements java.io.Serializable {


     private int id;
     private UserGroups userGroups;
     private String name;
     private int type;
     private Set optionItenses = new HashSet(0);
     private Set questionses = new HashSet(0);

    public Options() {
    }

	
    public Options(int id, String name, int type) {
        this.id = id;
        this.name = name;
        this.type = type;
    }
    public Options(int id, UserGroups userGroups, String name, int type, Set optionItenses, Set questionses) {
       this.id = id;
       this.userGroups = userGroups;
       this.name = name;
       this.type = type;
       this.optionItenses = optionItenses;
       this.questionses = questionses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public UserGroups getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(UserGroups userGroups) {
        this.userGroups = userGroups;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getOptionItenses() {
        return this.optionItenses;
    }
    
    public void setOptionItenses(Set optionItenses) {
        this.optionItenses = optionItenses;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }




}


