package com.checkdesk.control.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

/**
 * Permissions generated by hbm2java
 */
public class Permission
        implements java.io.Serializable
{
    private int id;
    private Group viewers;
    private String name;

    public Permission()
    {
    }

    public Permission(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public Permission(int id, Group viewers, String name)
    {
        this.id = id;
        this.viewers = viewers;
        this.name = name;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Group getViewers()
    {
        return this.viewers;
    }

    public void setViewers(Group viewers)
    {
        this.viewers = viewers;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }
}
