package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private int id;
     private Forms forms;
     private Options options;
     private String name;
     private int type;
     private String range;
     private Set questionAnswerses = new HashSet(0);

    public Questions() {
    }

	
    public Questions(int id, Forms forms, String name, int type, String range) {
        this.id = id;
        this.forms = forms;
        this.name = name;
        this.type = type;
        this.range = range;
    }
    public Questions(int id, Forms forms, Options options, String name, int type, String range, Set questionAnswerses) {
       this.id = id;
       this.forms = forms;
       this.options = options;
       this.name = name;
       this.type = type;
       this.range = range;
       this.questionAnswerses = questionAnswerses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Forms getForms() {
        return this.forms;
    }
    
    public void setForms(Forms forms) {
        this.forms = forms;
    }
    public Options getOptions() {
        return this.options;
    }
    
    public void setOptions(Options options) {
        this.options = options;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getRange() {
        return this.range;
    }
    
    public void setRange(String range) {
        this.range = range;
    }
    public Set getQuestionAnswerses() {
        return this.questionAnswerses;
    }
    
    public void setQuestionAnswerses(Set questionAnswerses) {
        this.questionAnswerses = questionAnswerses;
    }




}


