package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1



/**
 * QuestionAnswersId generated by hbm2java
 */
public class QuestionAnswersId  implements java.io.Serializable {


     private int refQuestion;
     private int refAnswer;

    public QuestionAnswersId() {
    }

    public QuestionAnswersId(int refQuestion, int refAnswer) {
       this.refQuestion = refQuestion;
       this.refAnswer = refAnswer;
    }
   
    public int getRefQuestion() {
        return this.refQuestion;
    }
    
    public void setRefQuestion(int refQuestion) {
        this.refQuestion = refQuestion;
    }
    public int getRefAnswer() {
        return this.refAnswer;
    }
    
    public void setRefAnswer(int refAnswer) {
        this.refAnswer = refAnswer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionAnswersId) ) return false;
		 QuestionAnswersId castOther = ( QuestionAnswersId ) other; 
         
		 return (this.getRefQuestion()==castOther.getRefQuestion())
 && (this.getRefAnswer()==castOther.getRefAnswer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRefQuestion();
         result = 37 * result + this.getRefAnswer();
         return result;
   }   


}


