package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1



/**
 * QuestionAnswers generated by hbm2java
 */
public class QuestionAnswers  implements java.io.Serializable {


     private QuestionAnswersId id;
     private Answers answers;
     private Questions questions;
     private String value;

    public QuestionAnswers() {
    }

    public QuestionAnswers(QuestionAnswersId id, Answers answers, Questions questions, String value) {
       this.id = id;
       this.answers = answers;
       this.questions = questions;
       this.value = value;
    }
   
    public QuestionAnswersId getId() {
        return this.id;
    }
    
    public void setId(QuestionAnswersId id) {
        this.id = id;
    }
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


