package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1



/**
 * RankStatementsId generated by hbm2java
 */
public class RankStatementsId  implements java.io.Serializable {


     private int refAnswers;
     private int refUser;

    public RankStatementsId() {
    }

    public RankStatementsId(int refAnswers, int refUser) {
       this.refAnswers = refAnswers;
       this.refUser = refUser;
    }
   
    public int getRefAnswers() {
        return this.refAnswers;
    }
    
    public void setRefAnswers(int refAnswers) {
        this.refAnswers = refAnswers;
    }
    public int getRefUser() {
        return this.refUser;
    }
    
    public void setRefUser(int refUser) {
        this.refUser = refUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RankStatementsId) ) return false;
		 RankStatementsId castOther = ( RankStatementsId ) other; 
         
		 return (this.getRefAnswers()==castOther.getRefAnswers())
 && (this.getRefUser()==castOther.getRefUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRefAnswers();
         result = 37 * result + this.getRefUser();
         return result;
   }   


}


