package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RankStatements generated by hbm2java
 */
public class RankStatements  implements java.io.Serializable {


     private RankStatementsId id;
     private Answers answers;
     private Users users;
     private BigDecimal score;

    public RankStatements() {
    }

    public RankStatements(RankStatementsId id, Answers answers, Users users, BigDecimal score) {
       this.id = id;
       this.answers = answers;
       this.users = users;
       this.score = score;
    }
   
    public RankStatementsId getId() {
        return this.id;
    }
    
    public void setId(RankStatementsId id) {
        this.id = id;
    }
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public BigDecimal getScore() {
        return this.score;
    }
    
    public void setScore(BigDecimal score) {
        this.score = score;
    }




}


