package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Surveys generated by hbm2java
 */
public class Surveys  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private Forms forms;
     private UserGroups userGroupsByRefParticipants;
     private UserGroups userGroupsByRefViewers;
     private Users users;
     private String title;
     private String info;
     private Date dtCreated;
     private int type;
     private Set answerses = new HashSet(0);

    public Surveys() {
    }

	
    public Surveys(int id, Categories categories, Forms forms, Users users, String title, String info, Date dtCreated, int type) {
        this.id = id;
        this.categories = categories;
        this.forms = forms;
        this.users = users;
        this.title = title;
        this.info = info;
        this.dtCreated = dtCreated;
        this.type = type;
    }
    public Surveys(int id, Categories categories, Forms forms, UserGroups userGroupsByRefParticipants, UserGroups userGroupsByRefViewers, Users users, String title, String info, Date dtCreated, int type, Set answerses) {
       this.id = id;
       this.categories = categories;
       this.forms = forms;
       this.userGroupsByRefParticipants = userGroupsByRefParticipants;
       this.userGroupsByRefViewers = userGroupsByRefViewers;
       this.users = users;
       this.title = title;
       this.info = info;
       this.dtCreated = dtCreated;
       this.type = type;
       this.answerses = answerses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Forms getForms() {
        return this.forms;
    }
    
    public void setForms(Forms forms) {
        this.forms = forms;
    }
    public UserGroups getUserGroupsByRefParticipants() {
        return this.userGroupsByRefParticipants;
    }
    
    public void setUserGroupsByRefParticipants(UserGroups userGroupsByRefParticipants) {
        this.userGroupsByRefParticipants = userGroupsByRefParticipants;
    }
    public UserGroups getUserGroupsByRefViewers() {
        return this.userGroupsByRefViewers;
    }
    
    public void setUserGroupsByRefViewers(UserGroups userGroupsByRefViewers) {
        this.userGroupsByRefViewers = userGroupsByRefViewers;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Date getDtCreated() {
        return this.dtCreated;
    }
    
    public void setDtCreated(Date dtCreated) {
        this.dtCreated = dtCreated;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set answerses) {
        this.answerses = answerses;
    }




}


