package com.checkdesk.control.data;
// Generated 09/08/2018 21:08:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String name;
     private String login;
     private String email;
     private String password;
     private String phone;
     private int type;
     private Set categorieses = new HashSet(0);
     private Set surveyses = new HashSet(0);
     private Set logses = new HashSet(0);
     private Set answerses = new HashSet(0);
     private Set rankStatementses = new HashSet(0);
     private Set userGroupses = new HashSet(0);

    public Users() {
    }

	
    public Users(int id, String name, String login, String email, String password, String phone, int type) {
        this.id = id;
        this.name = name;
        this.login = login;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.type = type;
    }
    public Users(int id, String name, String login, String email, String password, String phone, int type, Set categorieses, Set surveyses, Set logses, Set answerses, Set rankStatementses, Set userGroupses) {
       this.id = id;
       this.name = name;
       this.login = login;
       this.email = email;
       this.password = password;
       this.phone = phone;
       this.type = type;
       this.categorieses = categorieses;
       this.surveyses = surveyses;
       this.logses = logses;
       this.answerses = answerses;
       this.rankStatementses = rankStatementses;
       this.userGroupses = userGroupses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set categorieses) {
        this.categorieses = categorieses;
    }
    public Set getSurveyses() {
        return this.surveyses;
    }
    
    public void setSurveyses(Set surveyses) {
        this.surveyses = surveyses;
    }
    public Set getLogses() {
        return this.logses;
    }
    
    public void setLogses(Set logses) {
        this.logses = logses;
    }
    public Set getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set answerses) {
        this.answerses = answerses;
    }
    public Set getRankStatementses() {
        return this.rankStatementses;
    }
    
    public void setRankStatementses(Set rankStatementses) {
        this.rankStatementses = rankStatementses;
    }
    public Set getUserGroupses() {
        return this.userGroupses;
    }
    
    public void setUserGroupses(Set userGroupses) {
        this.userGroupses = userGroupses;
    }




}


