package com.checkdesk.model.data;
// Generated Aug 11, 2018 4:12:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Forms generated by hbm2java
 */
public class Form
        implements java.io.Serializable
{
    private int id;
    private Group viewers;
    private String name;
    private String info;
    private Set surveys = new HashSet(0);
    private Set questions = new HashSet(0);
    
    public Form()
    {
    }

    public Form(int id, String name, String info)
    {
        this.id = id;
        this.name = name;
        this.info = info;
    }

    public Form(int id, Group viewers, String name, String info, Set surveys, Set questions)
    {
        this.id = id;
        this.viewers = viewers;
        this.name = name;
        this.info = info;
        this.surveys = surveys;
        this.questions = questions;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Group getViewers()
    {
        return this.viewers;
    }

    public void setViewers(Group viewers)
    {
        this.viewers = viewers;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getInfo()
    {
        return this.info;
    }

    public void setInfo(String info)
    {
        this.info = info;
    }

    public Set getSurveys()
    {
        return this.surveys;
    }

    public void setSurveys(Set surveys)
    {
        this.surveys = surveys;
    }

    public Set getQuestions()
    {
        return this.questions;
    }

    public void setQuestions(Set questions)
    {
        this.questions = questions;
    }

    @Override
    public String toString()
    {
        return name;
    }
}
