package com.checkdesk.model.data;
// Generated Oct 21, 2018 7:39:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Option generated by hbm2java
 */
public class Option  implements java.io.Serializable {


     private int id;
     private Group viewers;
     private String name;
     private int type;
     private Set optionItens = new HashSet(0);
     private Set questions = new HashSet(0);

    public Option() {
    }

	
    public Option(String name, int type) {
        this.name = name;
        this.type = type;
    }
    public Option(Group viewers, String name, int type, Set optionItens, Set questions) {
       this.viewers = viewers;
       this.name = name;
       this.type = type;
       this.optionItens = optionItens;
       this.questions = questions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Group getViewers() {
        return this.viewers;
    }
    
    public void setViewers(Group viewers) {
        this.viewers = viewers;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getOptionItens() {
        return this.optionItens;
    }
    
    public void setOptionItens(Set optionItens) {
        this.optionItens = optionItens;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


