package com.checkdesk.model.data;
// Generated Oct 21, 2018 7:39:33 PM by Hibernate Tools 4.3.1



/**
 * QuestionAnswerId generated by hbm2java
 */
public class QuestionAnswerId  implements java.io.Serializable {


     private int questionId;
     private int answerId;

    public QuestionAnswerId() {
    }

    public QuestionAnswerId(int questionId, int answerId) {
       this.questionId = questionId;
       this.answerId = answerId;
    }
   
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public int getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }




}


