package com.checkdesk.model.data;
// Generated Oct 21, 2018 7:39:33 PM by Hibernate Tools 4.3.1



/**
 * RankStatementId generated by hbm2java
 */
public class RankStatementId  implements java.io.Serializable {


     private int answerId;
     private int userId;

    public RankStatementId() {
    }

    public RankStatementId(int answerId, int userId) {
       this.answerId = answerId;
       this.userId = userId;
    }
   
    public int getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


